services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PAYMENT_LINK
        sync: false
      - key: CONTACT_LINK
        sync: false
